In [1]:
import warnings
warnings.filterwarnings("ignore")
import shutil
import os
import pandas as pd
import matplotlib
matplotlib.use(u'nbAgg')
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pickle
from sklearn import preprocessing
import pandas as pd
import librosa
import IPython.display as ipd
import librosa.display
import sklearn

In [2]:
filename_split_order=np.load('filename_split_order.npy')
genre_predict4=np.load('genre_predict4.npy')
vgg_mel_spectrogram_split_order=np.load('vgg_mel_spectrogram_split_order.npy')

## genre_predict_f1:

In [3]:
genre_predict_f1=genre_predict4[:,1] #select the feature

In [4]:
genre_predict_f1.shape

(7997,)

In [5]:
order=np.argsort(-genre_predict_f1) #songs in decreasing order based on the selected feature

In [6]:
order=order[0:5] #top 5 songs 

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[0]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[1]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[2]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[3]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[4]])

#### Observation:
Maybe looking for certain frequencies

## genre_predict_f2:

In [236]:
genre_predict_f2=genre_predict4[:,2] #select the feature

In [237]:
genre_predict_f2.shape

(7997,)

In [238]:
order=np.argsort(-genre_predict_f2) #songs in decreasing order based on the selected feature

In [239]:
order=order[0:5] #top 5 songs 

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[0]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[1]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[2]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[3]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[4]])

#### Observation:
Hip-hop beats

## genre_predict_f3:

In [244]:
genre_predict_f3=genre_predict4[:,3]

In [245]:
genre_predict_f3.shape

(7997,)

In [246]:
order=np.argsort(-genre_predict_f3)

In [247]:
order=order[0:5]

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[0]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[1]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[2]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[3]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[4]])

#### Observation:
Vocals and  acoustic guitar

## genre_predict_f4:

In [38]:
genre_predict_f4=genre_predict4[:,4]

In [39]:
genre_predict_f4.shape

(7997,)

In [40]:
order=np.argsort(-genre_predict_f4)

In [41]:
order=order[0:5]

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[0]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[1]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[2]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[3]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[4]])

#### Observation:
Rap and Hip-Hop beats

## genre_predict_f5:

In [255]:
genre_predict_f5=genre_predict4[:,5]

In [256]:
genre_predict_f5.shape

(7997,)

In [257]:
order=np.argsort(-genre_predict_f5)

In [258]:
order=order[0:5]

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[0]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[1]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[2]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[3]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[4]])

#### Observation:
Folk/Middle Eastern

## genre_predict_f6:

In [56]:
genre_predict_f6=genre_predict4[:,6]

In [57]:
genre_predict_f6.shape

(7997,)

In [58]:
order=np.argsort(-genre_predict_f6)

In [59]:
order=order[0:5]

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[0]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[1]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[2]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[3]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[4]])

#### Observation:
String

## vgg_mel_spectrogram_split_order_f3123:

In [265]:
#looking for presence of non zero values
vgg_mel_spectrogram_split_order[0:60,3123]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 5.72567463, 4.30293798,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 5.23052788,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [266]:
vgg_mel_spectrogram_split_order_f3123=vgg_mel_spectrogram_split_order[:,3123]

In [267]:
vgg_mel_spectrogram_split_order_f3123.shape

(7997,)

In [268]:
order=np.argsort(-vgg_mel_spectrogram_split_order_f3123)

In [270]:
order=order[0:5]

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[0]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[1]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[2]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[3]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[4]])

#### Observation:
Guitar/distortion

## vgg_mel_spectrogram_split_order_f22901:

In [277]:
#looking for presence of non zero values
vgg_mel_spectrogram_split_order[0:60,22901]

array([7.1374402, 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ])

In [278]:
vgg_mel_spectrogram_split_order_f22901=vgg_mel_spectrogram_split_order[:,22901]

In [279]:
vgg_mel_spectrogram_split_order_f22901.shape

(7997,)

In [280]:
order=np.argsort(-vgg_mel_spectrogram_split_order_f22901)

In [282]:
order=order[0:5]

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[0]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[1]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[2]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[3]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[4]])

#### Observation:
clap/male voice

## vgg_mel_spectrogram_split_order_f1587:

In [211]:
#looking for presence of non zero values
vgg_mel_spectrogram_split_order[0:60,1587]

array([2.77685976, 0.        , 0.16194229, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 5.28880119, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 1.21976233, 3.3671844 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [212]:
vgg_mel_spectrogram_split_order_f3123=vgg_mel_spectrogram_split_order[:,1587]

In [213]:
vgg_mel_spectrogram_split_order_f3123.shape

(7997,)

In [214]:
order=np.argsort(-vgg_mel_spectrogram_split_order_f3123)

In [215]:
vgg_mel_spectrogram_split_order_f3123[order[0]]

47.155765533447266

In [216]:
order=order[0:5]

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[0]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[1]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[2]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[3]])

In [ ]:
ipd.Audio('/home/pravinshankar1/audios/'+filename_split_order[order[4]])

#### Observation:
bass?